#Specify names and barcodes for each sample
#Important to follow the ip-gtype-replicate naming system for the script to work
#Replicate must be a number. IP must be a single word without any hyphens.
samples:
    ha-wt-1 :   
      barcode: "ATCACG"
      group: "ha-wt"
      ip: "ha"
      gtype: "wt"
      replicate: 1
    ha-spt6-1 :   
      barcode: "CGATGT"
      group: "ha-spt6"
      ip: "ha"
      gtype: "spt6"
      replicate: 1
    ha-spt6-set2-1 :   
      barcode: "TTAGGC"
      group: "ha-spt6-set2"
      ip: "ha"
      gtype: "spt6-set2"
      replicate: 1
    ha-set2-1 :   
      barcode: "TGACCA"
      group: "ha-set2"
      ip: "ha"
      gtype: "set2"
      replicate: 1

    ha-wt-2 :   
      barcode: "ACAGTG"
      group: "ha-wt"
      ip: "ha"
      gtype: "wt"
      replicate: 2
    ha-spt6-2 :   
      barcode: "GCCAAT"
      group: "ha-spt6"
      ip: "ha"
      gtype: "spt6"
      replicate: 2
    ha-spt6-set2-2 :   
      barcode: "CAGATC"
      group: "ha-spt6-set2"
      ip: "ha"
      gtype: "spt6-set2"
      replicate: 2
    ha-set2-2 :   
      barcode: "ACTTGA"
      group: "ha-set2"
      ip: "ha"
      gtype: "set2"
      replicate: 2

    pol2-wt-1 :   
      barcode: "GATCAG"
      group: "pol2-wt"
      ip: "pol2"
      gtype: "wt"
      replicate: 1
    pol2-spt6-1 :   
      barcode: "TAGCTT"
      group: "pol2-spt6"
      ip: "pol2"
      gtype: "spt6"
      replicate: 1
    pol2-spt6-set2-1 :   
      barcode: "GGCTAC"
      group: "pol2-spt6-set2"
      ip: "pol2"
      gtype: "spt6-set2"
      replicate: 1
    pol2-set2-1 :   
      barcode: "CTTGTA"
      group: "pol2-set2"
      ip: "pol2"
      gtype: "set2"
      replicate: 1

    pol2-wt-2 :   
      barcode: "ATATAGGA"
      group: "pol2-wt"
      ip: "pol2"
      gtype: "wt"
      replicate: 2
    pol2-spt6-2 :   
      barcode: "AACCGTGT"
      group: "pol2-spt6"
      ip: "pol2"
      gtype: "spt6"
      replicate: 2
    pol2-spt6-set2-2 :   
      barcode: "AGGTCAGT"
      group: "pol2-spt6-set2"
      ip: "pol2"
      gtype: "spt6-set2"
      replicate: 2
    pol2-set2-2 :   
      barcode: "CTCTGTCT"
      group: "pol2-set2"
      ip: "pol2"
      gtype: "set2"
      replicate: 2

    h3k36me2-wt-1 :   
      barcode: "CCATACAC"
      group: "h3k36me2-wt"
      ip: "h3k36me2"
      gtype: "wt"
      replicate: 1
    h3k36me2-spt6-1 :   
      barcode: "CGCATTAA"
      group: "h3k36me2-spt6"
      ip: "h3k36me2"
      gtype: "spt6"
      replicate: 1
    h3k36me2-spt6-set2-1 :   
      barcode: "GTCTACAT"
      group: "h3k36me2-spt6-set2"
      ip: "h3k36me2"
      gtype: "spt6-set2"
      replicate: 1
    h3k36me2-set2-1 :   
      barcode: "GAGTTAAC"
      group: "h3k36me2-set2"
      ip: "h3k36me2"
      gtype: "set2"
      replicate: 1

    h3k36me2-wt-2 :   
      barcode: "GCAGCCTC"
      group: "h3k36me2-wt"
      ip: "h3k36me2"
      gtype: "wt"
      replicate: 2
    h3k36me2-spt6-2 :   
      barcode: "TCGCGTAC"
      group: "h3k36me2-spt6"
      ip: "h3k36me2"
      gtype: "spt6"
      replicate: 2
    h3k36me2-spt6-set2-2 :   
      barcode: "TATACCGT"
      group: "h3k36me2-spt6-set2"
      ip: "h3k36me2"
      gtype: "spt6-set2"
      replicate: 2
    h3k36me2-set2-2 :   
      barcode: "TGCGGTTA"
      group: "h3k36me2-set2"
      ip: "h3k36me2"
      gtype: "set2"
      replicate: 2

    h3k36me3-wt-1 :   
      barcode: "AACACCTAC"
      group: "h3k36me3-wt"
      ip: "h3k36me3"
      gtype: "wt"
      replicate: 1
    h3k36me3-spt6-1 :   
      barcode: "CCTTTACAG"
      group: "h3k36me3-spt6"
      ip: "h3k36me3"
      gtype: "spt6"
      replicate: 1
    h3k36me3-spt6-set2-1 :   
      barcode: "GGTCCTTGA"
      group: "h3k36me3-spt6-set2"
      ip: "h3k36me3"
      gtype: "spt6-set2"
      replicate: 1
    h3k36me3-set2-1 :   
      barcode: "TTGAGTGT"
      group: "h3k36me3-set2"
      ip: "h3k36me3"
      gtype: "set2"
      replicate: 1

    h3k36me3-wt-2 :   
      barcode: "ACTAACTGC"
      group: "h3k36me3-wt"
      ip: "h3k36me3"
      gtype: "wt"
      replicate: 2
    h3k36me3-spt6-2 :   
      barcode: "CAGGAGGCG"
      group: "h3k36me3-spt6"
      ip: "h3k36me3"
      gtype: "spt6"
      replicate: 2
    h3k36me3-spt6-set2-2 :   
      barcode: "GTTGTCCCA"
      group: "h3k36me3-spt6-set2"
      ip: "h3k36me3"
      gtype: "spt6-set2"
      replicate: 2
    h3k36me3-set2-2 :   
      barcode: "TGACGCAT"
      group: "h3k36me3-set2"
      ip: "h3k36me3"
      gtype: "set2"
      replicate: 2

    h3-wt-1 :   
      barcode: "ATCGCCAGC"
      group: "h3-wt"
      ip: "h3"
      gtype: "wt"
      replicate: 1
    h3-spt6-1 :   
      barcode: "CATTCCAAG"
      group: "h3-spt6"
      ip: "h3"
      gtype: "spt6"
      replicate: 1
    h3-spt6-set2-1 :   
      barcode: "GCAAGTAGA"
      group: "h3-spt6-set2"
      ip: "h3"
      gtype: "spt6-set2"
      replicate: 1
    h3-set2-1 :   
      barcode: "TGATCCGA"
      group: "h3-set2"
      ip: "h3"
      gtype: "set2"
      replicate: 1

    h3-wt-2 :   
      barcode: "ACGTAGCTC"
      group: "h3-wt"
      ip: "h3"
      gtype: "wt"
      replicate: 2
    h3-spt6-2 :   
      barcode: "CGAACTGTG"
      group: "h3-spt6"
      ip: "h3"
      gtype: "spt6"
      replicate: 2
    h3-spt6-set2-2 :   
      barcode: "TAGCTAGTA"
      group: "h3-spt6-set2"
      ip: "h3"
      gtype: "spt6-set2"
      replicate: 2
    h3-set2-2 :   
      barcode: "GTGGGATA"
      group: "h3-set2"
      ip: "h3"
      gtype: "set2"
      replicate: 2

    input-wt-1 :   
      barcode: "ATCCTATTC"
      group: "input-wt"
      ip: "input"
      gtype: "wt"
      replicate: 1
    input-spt6-1 :   
      barcode: "CGGACGTGG"
      group: "input-spt6"
      ip: "input"
      gtype: "spt6"
      replicate: 1
    input-spt6-set2-1 :   
      barcode: "GCGTTTCGA"
      group: "input-spt6-set2"
      ip: "input"
      gtype: "spt6-set2"
      replicate: 1
    input-set2-1 :   
      barcode: "TATCTCCG"
      group: "input-set2"
      ip: "input"
      gtype: "set2"
      replicate: 1

    input-wt-2 :   
      barcode: "CACAGTTGG"
      group: "input-wt"
      ip: "input"
      gtype: "wt"
      replicate: 2
    input-spt6-2 :   
      barcode: "GTGACTACA"
      group: "input-spt6"
      ip: "input"
      gtype: "spt6"
      replicate: 2
    input-spt6-set2-2 :   
      barcode: "TGAGAGTG"
      group: "input-spt6-set2"
      ip: "input"
      gtype: "spt6-set2"
      replicate: 2
    input-set2-2 :   
      barcode: "AATGCTGAC" 
      group: "input-set2"
      ip: "input"
      gtype: "set2"
      replicate: 2

#Provide name of the control genotype
control_gtype: "input"
      
#Provide name of the fastq file
fastq:
    "/n/groups/winston/rg161/chip-seq_pipeline/Undetermined_S0.R1.fastq.gz"
#Demultiplexing paramaters
demultiplex:
    #Number of bases in barcode for which a mismatch is permitted
    mismatch: 1
# Cutadapt quality cutoff parameters
cutadapt:
    qual_cutoff: 20
    min_length: 5

threads: 4

imagetype:
  plot_spikein_percentage: "png"
  plot_correlations: "png"
  plot_heatmap: "png"
  multi_metagene: "png"
  multi_metagene_divbylib: "png"
  metagene_bin_length_fpkm: "png"

#Plots excluding these samples will also be made in the mentioned rules
exclude:
  multi_metagene_divbylib: "spt6"

#Number of groups to divide genes into for length and fpkm binning
length_bins: 5
fpkm_bins: 5

normalizations:
  ha: 
    - input
    - pol2
  pol2: 
    - input
  h3k36me3: 
    - input
    - h3
    - ha
  h3k36me2:
    - input
    - h3
    - ha
  h3:
    - input

comparisons:
  #ha: input
  ha: pol2
  pol2: input
  h3k36me3: h3
  h3k36me2: h3
  h3: input
    
#Annotation details for plots that have to be made for S. cerevisiae and S. pombe
annotations:
  align-tss:
    refpoint: "TSS"
    upstream: 300
    downstream: 4000
    binstat: "mean"
    binsize: 20
    nan_afterend: "--nanAfterEnd"
    sort: "ascend"
    sortby: "region_length"
    missingdatacolor: 1
    reference_point: y
    bodylength: 0
    bed_suffix: "polIItranscripts-adjustedTSS"
    species: "all"
    length_fpkm: "y"
  align-tes:
    refpoint: "TES"
    upstream: 4000
    downstream: 300
    binstat: "mean"
    binsize: 20
    nan_afterend: "--nanAfterEnd"
    sort: "ascend"
    sortby: "region_length"
    missingdatacolor: 1 
    reference_point: y
    bodylength: 0
    bed_suffix: "polIItranscripts-adjustedTSS"
    species: "all"
    length_fpkm: "y"
  align-tss-tes:
    refpoint: "TSS-TES"
    upstream: 500
    downstream: 500
    binstat: "mean"
    binsize: 20
    nan_afterend: ""
    sort: "ascend"
    sortby: "region_length"
    missingdatacolor: 1 
    reference_point: n
    bodylength: 1000
    bed_suffix: "polIItranscripts-adjustedTSS"
    species: "all"
    length_fpkm: "y"
  align-coding-nov-tss:
    refpoint: "TSS"
    upstream: 300
    downstream: 4000
    binstat: "mean"
    binsize: 20
    nan_afterend: "--nanAfterEnd"
    sort: "ascend"
    sortby: "region_length"
    missingdatacolor: 1
    reference_point: y
    bodylength: 0
    bed_suffix: "transcripts_w_verifiedORFs-nonoverlapping"
    species: "Scer"
    length_fpkm: "y"
  align-coding-nov-tes:
    refpoint: "TES"
    upstream: 4000
    downstream: 300
    binstat: "mean"
    binsize: 20
    nan_afterend: "--nanAfterEnd"
    sort: "ascend"
    sortby: "region_length"
    missingdatacolor: 1 
    reference_point: y
    bodylength: 0
    bed_suffix: "transcripts_w_verifiedORFs-nonoverlapping"
    species: "Scer"
    length_fpkm: "y"
  align-coding-nov-tss-tes:
    refpoint: "TSS-TES"
    upstream: 500
    downstream: 500
    binstat: "mean"
    binsize: 20
    nan_afterend: ""
    sort: "ascend"
    sortby: "region_length"
    missingdatacolor: 1 
    reference_point: n
    bodylength: 1000
    bed_suffix: "transcripts_w_verifiedORFs-nonoverlapping"
    species: "Scer"
    length_fpkm: "y"

#Note that all the items for this dictionary need to be the same
callpeaks:
  h3k36me3: input
  h3k36me2: input
  ha: input
  pol2: input
  h3: input

macs2:
  fdr: 0.05
  env_name: python2

browser_shots:
  ADH1: minus
  STE11: plus
  TDH3: minus
  RIX1: plus
